Adding deauth code option
aircrack-ng/aircrack-ng-archive pull request #99
Opened 2017-02-19 20:13 UTC by pocchoc

2017-02-20 03:19 UTC, aircrack-ng requested changes
Could you update the patch according to the review?

2017-02-20 03:19 UTC, aircrack-ng commented on src/aireplay-ng.c
> +	    /* deauthenticate the target */
Could you not modify this indentation (even if incorrect)?

2017-02-20 03:19 UTC, aircrack-ng commented on src/aireplay-ng.c
> +            memcpy( h80211 + 24, &(opt.deauthreason), 1);
I don't think memcpy is necessary here, we're modifying a single byte of data.

2017-02-20 03:19 UTC, aircrack-ng commented on src/aireplay-ng.c
> +            memcpy( h80211 + 24, &(opt.deauthreason), 1);
Same as previous, I don't think memcpy is necessary, it's a single byte.

2017-02-20 03:19 UTC, aircrack-ng commented on src/aireplay-ng.c
> +    int deauthreason;
You should use unsigned char instead.

2017-02-20 03:19 UTC, aircrack-ng commented on src/aireplay-ng.c
> +
Please remove the empty line

2017-02-20 03:19 UTC, aircrack-ng commented on src/aireplay-ng.c
> +                ret = sscanf( optarg, "%d", &opt.deauthreason );
This might need to be modified when switching to unsigned char for opt.deauthreason

2017-02-21 07:00 UTC, pocchoc commented
Thanks for the pointers, I've updated the sections as requested and re-tested.

2017-10-21 18:55 UTC, aircrack-ng commented
Committed in [r2930](http://trac.aircrack-ng.org/changeset/2930) (fixed indentation of some code) and slightly modified in [r2931](http://trac.aircrack-ng.org/changeset/2931).

2017-10-21 18:55 UTC, closed without merging